dpro55/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register, name='register')
]

food/urls.py
from . import views
from django.urls import path

app_name = 'food'

urlpatterns = [
    #food
    path('', views.index,name='index'),
    #food/1
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),

    #add items
    path('add',views.create_item,name="create_item"),
   
    #edit items
    path('update/<int:id>/',views.update_item,name="update_item"),

    #delete item
    path('delete/<int:id>/',views.delete_item,name="delete_item"),

]

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
        

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
#from django.template import loader

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    #template = loader.get_template('food/index.html')
    context ={'item_list':item_list}
    return render(request,'food/index.html',context)


def item(request):
    return HttpResponse("<h1>This is item view</h1>")


def detail(request, item_id):
    item = Item.objects.get(pk = item_id)
    context = {'item':item}
    return render(request,'food/detail.html' ,context)
    #return HttpResponse("This is item no/id: %s" % item_id)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)

    form = ItemForm(request.POST or None,instance= item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item} )


def delete_item(request,id):
    item = Item.objects.get(id=id)
    
    if item:
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome{username}, your account is created')
            return redirect('food:index')
    else:    
        form = UserCreationForm()
    return render(request, 'users/register.html',{'form':form })

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'food/style.css'  %}"  rel="stylesheet" >
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-dark bg-dark"> 

        <a href="#" class="navbar-brand">FoodApp</a>
       
        <div class ="navbar" >           
            <a class="nav-item nav-link badge text-bg-primary" href ="{% url 'food:create_item' %}"  >Add Item </a>  
            <a class="nav-item nav-link badge text-bg-primary" href ='#'  >Delete Item</a>  
            <a class="nav-item nav-link badge text-bg-primary" href ='#'  >View Item</a>  
        </div>
       
    
    </nav>

{% block body %}

{% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src = "{{item.item_image}}" class="card">
            
        </div>
        <div class="col-md-6" >
            <h1>{{item.item_name}}</h1>
            <h1>{{item.item_desc}}</h1>
            <h1>${{item.item_price}}</h1>
            
        </div>

    </div>

</div>


{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!--{% load static %}
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
<body>
   
    {% block body %}
         
        
        {%for item in item_list%}

        <div class="row">
            <div class="col-md-2 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}">                
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h4>{{item.item_desc}}</h4>
                <h5>${{item.item_price}}</h5>
            </div>
            <div class="col-md-3">
                <!--<a href = "{% url 'food:detail' item.id %}">{{item.id}}  --- {{item.item_name}}</a>-->
                <a href ="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                <a href ="{% url 'food:update_item' item.id %}" class="btn btn-success">update</a>
                <a href ="{% url 'food:delete_item' item.id %}" class="btn btn-success">delete</a>
                
            </div>
        </div>
        <!--
        <ul>
            <li>
             
             <a href = "{% url 'food:detail' item.id %}">{{item.id}}  --- {{item.item_name}}</a>
             {{item.id}}  --- {{item.item_name}}
             
            

             <a href = "{% url 'food:detail' item.id %}">{{item.id}}  --- {{item.item_name}}</a>
        
            </li>
        </ul>
        
        -->
        
         
        {%endfor%} 
    </body>
{% endblock %}
   
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}
<form>
    {% csrf_token%}

    <h2>Are you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/register.html
<form method="POST">
    {% csrf_token%}
    {{form}}
    <button type="submit">signup</button>
</form>